const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { easter } = require('../acnh-diary-mobile/node_modules/date-easter');
const root = path.resolve(__dirname, '../acnh-diary-mobile/src/data');
const { events } = require('../acnh-diary-mobile/src/data/content/catalog/nook-shopping-events.json');
const { items } = require('../acnh-diary-mobile/src/data/content/catalog/catalog.json');
const lunar = new Intl.DateTimeFormat('en-u-ca-chinese', { month: 'numeric', day: 'numeric', timeZone: 'UTC' });
assert.equal(lunar.resolvedOptions().calendar, 'chinese');
const dayMs = 86400000;
const code = date => (date.getUTCMonth() + 1) * 100 + date.getUTCDate();
const shifted = (date, days) => code(new Date(date.getTime() + days * dayMs));
const years = {};
for (let year = 2000; year <= 2060; year++) {
  const dates = {};
  for (let date = new Date(Date.UTC(year, 0, 1)); date.getUTCFullYear() === year; date = new Date(+date + dayMs)) {
    const parts = lunar.formatToParts(date);
    const month = parts.find(p => p.type === 'month').value;
    const day = parts.find(p => p.type === 'day').value;
    const key = { '1/1': 'lunar-new-year', '5/5': 'dragon-boat', '7/7': 'qixi', '8/15': 'moon' }[`${month}/${day}`];
    if (key) dates[key] = key === 'lunar-new-year' ? [shifted(date, -2), shifted(date, 5)] : [shifted(date, -9), code(date)];
  }
  const pascha = easter(year);
  const easterDate = new Date(Date.UTC(year, pascha.month - 1, pascha.day));
  dates.carnival = [shifted(easterDate, -69), shifted(easterDate, -47)];
  assert.equal(Object.keys(dates).length, 5, `Missing dates for ${year}`);
  years[year] = dates;
}
fs.writeFileSync(path.join(root, 'content/catalog/nook-shopping-years.json'), JSON.stringify({ schemaVersion: 1, years }, null, 2) + '\n');

// Reuse only the seasonal product assets already present in the native registry.
const names = new Set(events.flatMap(event => event.items));
const seasonal = items.filter(item => names.has(item.nameEn));
assert.equal(seasonal.length, names.size, 'Every scheduled product must resolve to exactly one catalog item');
const native = fs.readFileSync(path.join(root, 'catalog-assets.ts'), 'utf8').split(/\r?\n/);
const rows = seasonal.map(item => {
  const prefix = `  ${JSON.stringify(`${item.assetType}/${item.assetId}`)}:`;
  const row = native.find(line => line.startsWith(prefix));
  assert.ok(row, `Missing local asset: ${item.nameEn}`);
  return row;
});
fs.writeFileSync(path.join(root, 'nook-shopping-assets.ts'), [
  '// Generated by scripts/build_nook_shopping_data.cjs.',
  "import type { ImageSourcePropType } from 'react-native';", '',
  'export const nookShoppingAssets: Record<string, ImageSourcePropType> = {',
  ...rows, '};', '',
].join('\n'));
console.log(`Generated 2000-2060 moving dates and ${seasonal.length} local seasonal product assets.`);
